dist: trusty

services:
  - docker

language: java

jdk:
  - oraclejdk8

env:
  - CI_PROFILE=gemflux
  - CI_PROFILE=starrsem
  - CI_PROFILE=starflux
  - CI_PROFILE=markdup
  - CI_PROFILE=rmdup
  - CI_PROFILE=ihec

script:
  - . .circ && ci test